/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/models/Chan.glb --output src/components/Chan-full.tsx --types --keepgroups --keepmeshes --shadows 
*/

import * as THREE from 'three'
import React from 'react'
import { type ThreeElements } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props: Readonly<ThreeElements['group']>) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, animations } = useGLTF('/Chan.glb')
  useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="bodychan-rig" position={[-0.75, 0, 0]}>
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-spinehip_ik']} />
          <primitive object={nodes['MCH-shoulderikL']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-forearm_ik_midparentL']} />
          <primitive object={nodes['MCH-held-objectparentL']} />
          <primitive object={nodes['MCH-f_index01_ikparentL']} />
          <primitive object={nodes['MCH-thumb01_ikparentL']} />
          <primitive object={nodes['MCH-f_middle01_ikparentL']} />
          <primitive object={nodes['MCH-f_ring01_ikparentL']} />
          <primitive object={nodes['MCH-f_pinky01_ikparentL']} />
          <primitive object={nodes['MCH-shoulderikR']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-forearm_ik_midparentR']} />
          <primitive object={nodes['MCH-held-objectparentR']} />
          <primitive object={nodes['MCH-f_index01_ikparentR']} />
          <primitive object={nodes['MCH-thumb01_ikparentR']} />
          <primitive object={nodes['MCH-f_middle01_ikparentR']} />
          <primitive object={nodes['MCH-f_ring01_ikparentR']} />
          <primitive object={nodes['MCH-f_pinky01_ikparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-shin_ik_midparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <primitive object={nodes['MCH-shin_ik_midparentR']} />
          <primitive object={nodes['MCH-lip_armBL001']} />
          <primitive object={nodes['MCH-lip_armBR001']} />
          <primitive object={nodes['MCH-lip_armTL001']} />
          <primitive object={nodes['MCH-lip_armTR001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Chan.glb')
